version: 1
formatters:
  default:
    format: '%(asctime)s [%(name)s] [%(levelname)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: ${LOG_DIR}/vi_monitor.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

loggers:
  VIMonitor:
    level: INFO
    handlers: [console, file]
    propagate: false 